from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PROJECT = ROOT.parents[2]
sys.path.insert(0, str(PROJECT / "src"))

from spoolfinish.material import mass_g
from spoolfinish.parser import analyze_text
from spoolfinish.patcher import patch
from spoolfinish.planner import PlanError, plan_change

RELEASE = "2.9.6"
SOURCE = "https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.9.6"
START_GCODE = "G21\nG90\nM83\nG1 E3 F240"
LAYER_GCODE = "G92 E0"
METADATA_MM = re.compile(r"^; filament used \[mm\] = ([0-9]+(?:\.[0-9]+)?)$", re.M)


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def portable_manifest_argument(argument: str) -> str:
    """Keep paths in the proof manifest portable and free of machine details."""
    path = Path(argument)
    if not path.is_absolute():
        return argument
    try:
        return path.resolve().relative_to(PROJECT.resolve()).as_posix()
    except ValueError:
        # The external slicer executable is useful to identify by name, but its
        # installation location is specific to the machine running the test.
        return path.name


def run(slicer: Path) -> dict:
    slicer = slicer.resolve()
    if not slicer.is_file():
        raise FileNotFoundError(f"PrusaSlicer CLI not found: {slicer}")

    model = ROOT / "cube_20mm.stl"
    gcode = ROOT / "plate_1.gcode"
    if not model.is_file():
        raise FileNotFoundError(model)

    options = [
        "--export-gcode", "--output", str(gcode),
        "--layer-height", "0.2", "--first-layer-height", "0.2",
        "--filament-diameter", "1.75", "--nozzle-diameter", "0.4",
        "--filament-type", "PLA", "--gcode-flavor", "marlin",
        "--use-relative-e-distances", "--layer-gcode", LAYER_GCODE,
        "--filament-retract-lift", "0.2", "--start-gcode", START_GCODE,
        "--first-layer-temperature", "210", "--temperature", "210",
        str(model),
    ]
    result = subprocess.run([str(slicer), *options], cwd=ROOT, capture_output=True,
                            text=True, timeout=600)
    if result.returncode:
        raise RuntimeError(f"PrusaSlicer exited {result.returncode}: {result.stderr[-2000:]} {result.stdout[-2000:]}")
    if not gcode.is_file():
        raise RuntimeError("PrusaSlicer did not produce G-code")

    text = gcode.read_text(encoding="utf-8")
    header = "\n".join(text.splitlines()[:5])
    version_match = re.search(r"generated by PrusaSlicer ([^ ]+)", header)
    if not version_match or version_match.group(1) != RELEASE:
        raise RuntimeError("Generated G-code does not identify official PrusaSlicer 2.9.6")
    oracle_match = METADATA_MM.search(text)
    if not oracle_match:
        raise RuntimeError("PrusaSlicer G-code has no filament used [mm] oracle")

    analysis = analyze_text(text)
    oracle_mm = Decimal(oracle_match.group(1))
    diff_mm = abs(Decimal(str(analysis.total_mm)) - oracle_mm)
    tolerance_mm = Decimal("0.0051")  # two decimal places, rounded to nearest 0.01 mm
    if diff_mm > tolerance_mm:
        raise AssertionError(f"length oracle delta {diff_mm} mm > {tolerance_mm} mm")
    if abs(analysis.startup_mm - 3.0) > 1e-9:
        raise AssertionError(f"startup prime not counted as expected: {analysis.startup_mm} mm")
    if not analysis.layers or any(layer.z_mm is None for layer in analysis.layers):
        raise AssertionError("deterministic layer Z metadata missing")
    if any(a.z_mm >= b.z_mm for a, b in zip(analysis.layers, analysis.layers[1:])):
        raise AssertionError("layer Z metadata is not strictly increasing")
    if len(analysis.layers) != 100:
        raise AssertionError(f"expected 100 explicit layer markers, got {len(analysis.layers)}")
    modes = sorted(set(re.findall(r"^\s*(M82|M83)\b", text, re.M | re.I)))
    modes = [m.upper() for m in modes]
    if modes != ["M83"]:
        raise AssertionError(f"expected only explicit relative extrusion mode, got {modes}")

    z_moves = re.findall(r"^\s*G[01]\s+[^;]*\bZ[+-]?(?:\d+(?:\.\d*)?|\.\d+)", text, re.M | re.I)
    z_hop_moves = [line for line in z_moves if re.search(r"\bZ(?:\.4|0\.4)\b", line)]
    if len(z_moves) <= len(analysis.layers) or not z_hop_moves:
        raise AssertionError("expected retraction Z-hop moves in addition to 100 layer boundaries")

    layer_extrusion_mm = sum(layer.consumed_mm for layer in analysis.layers)
    if abs(analysis.startup_mm + layer_extrusion_mm - analysis.total_mm) > 1e-8:
        raise AssertionError("startup and per-layer extrusion do not reconcile with total")

    total_g = mass_g(analysis.total_mm, "PLA", 1.75)
    reserve_g = 0.2
    remaining_g = total_g * 0.65 + reserve_g
    plan = plan_change(analysis, remaining_g, reserve_g, "PLA", 1.75)
    if not plan.change_required or plan.change_before_layer is None:
        raise AssertionError("normal safe-change scenario did not select a change boundary")
    selected_mm = analysis.startup_mm if plan.last_completed_layer is None else analysis.layers[plan.last_completed_layer].cumulative_mm
    if abs(plan.consumed_before_g - mass_g(selected_mm, "PLA")) > 1e-9:
        raise AssertionError("safe-change consumption does not match completed layer")
    if plan.consumed_before_g > plan.usable_g + 1e-10:
        raise AssertionError("selected completed layer exceeds usable material")
    next_layer = analysis.layers[plan.change_before_layer]
    next_complete_g = mass_g(next_layer.cumulative_mm, "PLA")
    if next_complete_g <= plan.usable_g + 1e-10:
        raise AssertionError("next complete layer still fits in usable material")

    exact_mm = analysis.layers[49].cumulative_mm
    exact = plan_change(analysis, mass_g(exact_mm, "PLA") + reserve_g, reserve_g, "PLA", 1.75)
    inside_mm = exact_mm + analysis.layers[50].consumed_mm * 0.25
    inside = plan_change(analysis, mass_g(inside_mm, "PLA") + reserve_g, reserve_g, "PLA", 1.75)
    if exact.change_before_layer != 50 or inside.change_before_layer != 50:
        raise AssertionError("exact-boundary or inside-next-layer case selected the wrong boundary")
    try:
        plan_change(analysis, 0.1, 0.2, "PLA", 1.75)
    except PlanError:
        pass
    else:
        raise AssertionError("reserve greater than remaining did not fail")
    fits = plan_change(analysis, total_g + reserve_g + 0.01, reserve_g, "PLA", 1.75)
    if fits.change_required:
        raise AssertionError("print that fits should require no material change")

    original = gcode.read_bytes()
    original_hash = sha(gcode)
    patch_results = {}
    for firmware, command, name in (
        ("marlin", "M600", "plate_1_marlin.gcode"),
        ("klipper", "PAUSE", "plate_1_klipper.gcode"),
    ):
        output = ROOT / name
        output.unlink(missing_ok=True)
        patched = patch(gcode, output, plan, firmware).read_bytes()
        block = f"; SPOOLFINISH_CHANGE_BEGIN\n{command}\n; SPOOLFINISH_CHANGE_END\n".encode()
        command_lines = re.findall(rb"(?m)^" + command.encode() + rb"\s*$", patched)
        if patched.count(block) != 1 or len(command_lines) != 1:
            raise AssertionError(f"{firmware}: pause injection is not exactly once")
        if patched.replace(block, b"", 1) != original:
            raise AssertionError(f"{firmware}: unrelated source bytes changed")
        if patched.index(block) != len(b"".join(original.splitlines(keepends=True)[:plan.boundary_line])):
            raise AssertionError(f"{firmware}: patch is not at the selected layer boundary")
        reparsed = analyze_text(patched.decode("utf-8"))
        if len(reparsed.layers) != len(analysis.layers) or abs(reparsed.total_mm - analysis.total_mm) > 1e-8:
            raise AssertionError(f"{firmware}: patched output does not reparse identically")
        patch_results[firmware] = {"command": command, "count": 1, "change_before_layer": plan.change_before_layer,
                                   "only_injected_block_diff": True, "reparse": "PASS", "output": name}
    if sha(gcode) != original_hash or gcode.read_bytes() != original:
        raise AssertionError("generated source changed during patch validation")

    manifest_arguments = [portable_manifest_argument(argument) for argument in options]
    manifest = {
        "slicer": "PrusaSlicer", "slicer_version": RELEASE, "source": SOURCE,
        "source_sha256": "5aaf22e42f95accecfa122d23a835911f289ecc2ff606db3e83d637ddcc0a209",
        "command_executable": slicer.name, "command_arguments": manifest_arguments,
        "command": [slicer.name, *manifest_arguments],
        "model": "same locally generated closed 20 mm cube as Orca simulation",
        "profile_basis": "official PrusaSlicer CLI defaults with explicit deterministic FDM/PLA overrides; no named printer profile",
        "output_gcode": gcode.name, "source_gcode_sha256": original_hash,
        "extrusion_modes": modes, "layer_marker": ";LAYER_CHANGE", "layers": len(analysis.layers),
        "z_motion_moves": len(z_moves), "z_hop_moves_to_0_4mm": len(z_hop_moves),
        "layer_z_first_mm": analysis.layers[0].z_mm, "layer_z_last_mm": analysis.layers[-1].z_mm,
        "startup_filament_mm": analysis.startup_mm, "total_filament_mm": analysis.total_mm,
        "oracle": {"source": "; filament used [mm] in generated G-code", "reported_mm": float(oracle_mm),
                   "metadata_precision_mm": 0.01, "spoolfinish_mm": analysis.total_mm,
                   "absolute_difference_mm": float(diff_mm), "relative_difference_percent": float(diff_mm / oracle_mm * 100),
                   "tolerance_mm": float(tolerance_mm), "mass_metadata_g": None,
                   "mass_note": "PrusaSlicer emitted total filament used [g] = 0.00 with the CLI default filament profile; mm is the primary oracle."},
        "safe_change": {"remaining_g": remaining_g, "reserve_g": reserve_g, "usable_g": plan.usable_g,
                        "last_completed_layer": plan.last_completed_layer, "change_before_layer": plan.change_before_layer,
                        "change_z_mm": plan.change_z, "consumed_before_change_g": plan.consumed_before_g,
                        "next_layer_cumulative_g": next_complete_g,
                        "consumed_before_le_usable": plan.consumed_before_g <= plan.usable_g,
                        "consumed_through_next_layer_gt_usable": next_complete_g > plan.usable_g},
        "edge_simulations": {"exact_boundary_change_before_layer": exact.change_before_layer,
                             "inside_next_layer_change_before_layer": inside.change_before_layer,
                             "reserve_greater_than_remaining": "ERROR", "whole_print_fits": "NO_CHANGE"},
        "patches": patch_results, "source_unchanged": True, "firmware_runtime_proven": False,
    }
    (ROOT / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--slicer", type=Path, required=True)
    arguments = parser.parse_args()
    print(json.dumps(run(arguments.slicer), indent=2))
