from __future__ import annotations
import argparse, hashlib, json, os, re, subprocess, sys, tempfile, xml.etree.ElementTree as ET
from pathlib import Path
from zipfile import ZipFile
from decimal import Decimal
ROOT = Path(__file__).resolve().parent
PROJECT = ROOT.parents[2]
sys.path.insert(0, str(PROJECT / "src"))
from spoolfinish.parser import analyze_text
from spoolfinish.planner import plan_change, PlanError
from spoolfinish.patcher import patch
from spoolfinish.material import mass_g

def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()

def run(slicer: Path) -> dict:
    slicer=slicer.resolve()
    if not slicer.is_file(): raise FileNotFoundError(f"OrcaSlicer CLI not found: {slicer}")
    model=ROOT/'cube_20mm.stl'; gcode=ROOT/'plate_1.gcode'; archive=ROOT/'cube_sliced.3mf'
    if not model.is_file(): raise FileNotFoundError(model)
    with tempfile.TemporaryDirectory(prefix='spoolfinish-orca-') as temp:
        temp=Path(temp)
        args=[str(slicer),'--debug','5','--logfile',str(temp/'orca.log'),'--datadir',str(temp/'user-profile'),
              '--load-settings',str(ROOT/'machine.json')+';'+str(ROOT/'process.json'),
              '--load-filaments',str(ROOT/'filament.json'),'--outputdir',str(ROOT),'--slice','0',
              '--export-3mf','cube_sliced.3mf',str(model)]
        result=subprocess.run(args,cwd=ROOT,capture_output=True,text=True,timeout=600)
        if result.returncode: raise RuntimeError(f"OrcaSlicer exited {result.returncode}: {result.stderr[-2000:]} {result.stdout[-2000:]}")
    if not gcode.is_file() or not archive.is_file(): raise RuntimeError('OrcaSlicer did not produce both G-code and 3MF')
    text=gcode.read_text(encoding='utf-8'); header='\n'.join(text.splitlines()[:5])
    version_match=re.search(r'generated by OrcaSlicer ([^ ]+)',header)
    if not version_match: raise RuntimeError('generated G-code has no OrcaSlicer version header')
    version=version_match.group(1)
    with ZipFile(archive) as z:
        info=ET.fromstring(z.read('Metadata/slice_info.config'))
    filament=info.find('.//filament')
    if filament is None or 'used_m' not in filament.attrib or 'used_g' not in filament.attrib:
        raise RuntimeError('No slicer-reported used_m/used_g oracle in Metadata/slice_info.config')
    oracle_mm=float(Decimal(filament.attrib['used_m'])*Decimal(1000)); oracle_g=float(filament.attrib['used_g'])
    analysis=analyze_text(text)
    mm_diff=abs(analysis.total_mm-oracle_mm); calculated_g=mass_g(analysis.total_mm,'PLA',1.75,1.24); g_diff=abs(calculated_g-oracle_g)
    mm_tol=5.01; g_tol=0.0051
    if mm_diff>mm_tol: raise AssertionError(f'length oracle delta {mm_diff:.6f} mm > {mm_tol} mm')
    if g_diff>g_tol: raise AssertionError(f'mass oracle delta {g_diff:.6f} g > {g_tol} g')
    modes=re.findall(r'^\s*(M82|M83)\b',text,re.M|re.I)
    mode_set=sorted(set(m.upper() for m in modes))
    if 'M83' not in mode_set: raise AssertionError('expected explicit M83 in real output')
    if not analysis.startup_mm>0: raise AssertionError('startup/purge extrusion was not counted')
    if len(analysis.layers)<50: raise AssertionError(f'implausible cube layer count: {len(analysis.layers)}')
    if any(layer.z_mm is None for layer in analysis.layers): raise AssertionError('real layer Z metadata missing')
    if any(analysis.layers[i].z_mm >= analysis.layers[i+1].z_mm for i in range(len(analysis.layers)-1)): raise AssertionError('layer Z is not strictly increasing')
    z_moves=len(re.findall(r'^\s*G[01]\s+[^;]*\bZ[+-]?(?:\d+(?:\.\d*)?|\.\d+)',text,re.M|re.I))
    if z_moves<=len(analysis.layers): raise AssertionError('profile did not generate Z-hop motion in addition to layer Z moves')
    total_g=mass_g(analysis.total_mm,'PLA'); reserve=0.2; remaining=total_g*0.65+reserve
    plan=plan_change(analysis,remaining,reserve,'PLA',1.75)
    if not plan.change_required or plan.change_before_layer is None: raise AssertionError('normal safe-change simulation failed')
    selected=plan.last_completed_layer; cumulative=analysis.startup_mm if selected is None else analysis.layers[selected].cumulative_mm
    if abs(plan.consumed_before_g-mass_g(cumulative,'PLA'))>1e-9: raise AssertionError('planner consumption does not match completed layers')
    if plan.consumed_before_g>plan.usable_g+1e-10: raise AssertionError('selected boundary exceeds usable filament')
    next_layer=analysis.layers[plan.change_before_layer]
    if mass_g(next_layer.cumulative_mm,'PLA')<=plan.usable_g+1e-10: raise AssertionError('following full layer unexpectedly fits')
    exact_limit=mass_g(analysis.layers[49].cumulative_mm,'PLA')
    exact=plan_change(analysis,exact_limit+reserve,reserve,'PLA',1.75)
    inside_limit=exact_limit+mass_g(analysis.layers[50].consumed_mm,'PLA')*0.25
    inside=plan_change(analysis,inside_limit+reserve,reserve,'PLA',1.75)
    if exact.change_before_layer!=50 or inside.change_before_layer!=50: raise AssertionError('exact/inside layer edge chose wrong boundary')
    try: plan_change(analysis,0.1,0.2,'PLA',1.75)
    except PlanError: pass
    else: raise AssertionError('reserve > remaining did not fail')
    fitting=plan_change(analysis,total_g+reserve+0.01,reserve,'PLA',1.75)
    if fitting.change_required: raise AssertionError('complete print fit but planner required a change')
    tiny=plan_change(analysis,mass_g(analysis.startup_mm,'PLA')+reserve+0.001,reserve,'PLA',1.75)
    if tiny.change_before_layer!=0: raise AssertionError('very small spool should switch before first model layer')
    override=plan_change(analysis,remaining,reserve,'PLA',1.75,1.30)
    if override.total_g<=plan.total_g: raise AssertionError('custom PLA density override had no effect')
    cli_env=dict(os.environ);cli_env['PYTHONPATH']=str(PROJECT/'src')+os.pathsep+cli_env.get('PYTHONPATH','')
    with tempfile.TemporaryDirectory(prefix='spoolfinish-density-') as density_temp:
        density_output=Path(density_temp)/'density.gcode'
        cli=subprocess.run([sys.executable,'-m','spoolfinish.cli','analyze',str(gcode),'--remaining',str(remaining),
          '--reserve',str(reserve),'--material','PLA','--density','1.30','--output',str(density_output)],
          cwd=PROJECT,env=cli_env,capture_output=True,text=True,timeout=60)
        if cli.returncode or not density_output.is_file(): raise AssertionError(f'CLI density override failed: {cli.stdout} {cli.stderr}')
        cli_total=float(re.search(r'^TOTAL_REQUIRED_G=([0-9.]+)$',cli.stdout,re.M).group(1))
        if abs(cli_total-override.total_g)>0.0051: raise AssertionError('CLI density override differs from planner')
    original=gcode.read_bytes(); source_hash=sha(gcode); patch_results={}
    for firmware,command,output_name in [('marlin','M600','plate_1_marlin.gcode'),('klipper','PAUSE','plate_1_klipper.gcode')]:
        fd,temporary=tempfile.mkstemp(prefix='spoolfinish-patch-',suffix='.gcode',dir=ROOT);os.close(fd);Path(temporary).unlink()
        patched=patch(gcode,Path(temporary),plan,firmware); data=patched.read_bytes(); patched.unlink()
        block=f'; SPOOLFINISH_CHANGE_BEGIN\n{command}\n; SPOOLFINISH_CHANGE_END\n'.encode()
        if data.count(command.encode())!=1 or data.count(block)!=1: raise AssertionError(f'{firmware}: injected command/block count is not exactly one')
        if data.replace(block,b'',1)!=original: raise AssertionError(f'{firmware}: source bytes differ outside injected block')
        reparsed=analyze_text(data.decode('utf-8'))
        if len(reparsed.layers)!=len(analysis.layers) or abs(reparsed.total_mm-analysis.total_mm)>1e-8: raise AssertionError(f'{firmware}: patched G-code did not reparse identically')
        (ROOT/output_name).write_bytes(data)
        patch_results[firmware]={'command':command,'count':1,'only_injected_block_diff':True,'reparse':'PASS','output':output_name}
    source_hash_after=sha(gcode)
    if source_hash_after!=source_hash or original!=gcode.read_bytes(): raise AssertionError('original G-code changed')
    manifest={'slicer':'OrcaSlicer','slicer_version':version,'release':'official Windows x64 portable v2.4.2',
      'profile':'Prusa MK3S 0.4 nozzle; 0.20mm Standard @MK3S; Prusa Generic PLA','model':'local closed 20 mm cube',
      'output_gcode':'plate_1.gcode','input_gcode_sha256':source_hash,'source_hash_before_patch':source_hash,
      'extrusion_modes':mode_set,'layer_marker':';LAYER_CHANGE','layers':len(analysis.layers),'z_motion_moves':z_moves,'startup_filament_mm':analysis.startup_mm,
      'total_filament_mm':analysis.total_mm,'density_g_cm3':1.24,
      'oracle':{'source':'cube_sliced.3mf:Metadata/slice_info.config','used_m':float(filament.attrib['used_m']),'used_g':oracle_g,
        'spoolfinish_mm':analysis.total_mm,'absolute_mm_difference':mm_diff,'relative_percent_difference':100*mm_diff/oracle_mm,
        'length_tolerance_mm':mm_tol,'spoolfinish_g':calculated_g,'absolute_g_difference':g_diff,'mass_tolerance_g':g_tol},
      'safe_change':{'remaining_g':remaining,'reserve_g':reserve,'usable_g':plan.usable_g,'last_completed_layer':plan.last_completed_layer,
        'change_before_layer':plan.change_before_layer,'change_z_mm':plan.change_z,'consumed_before_change_g':plan.consumed_before_g,
        'expected_remainder_g':plan.remainder_g,'next_layer_cumulative_g':mass_g(next_layer.cumulative_mm,'PLA')},
      'edge_simulations':{'exact_boundary_layer':exact.change_before_layer,'inside_next_layer_boundary':inside.change_before_layer,
        'reserve_greater_than_remaining':'ERROR','complete_print_fits':'NO_CHANGE','very_small_spool_before_layer':tiny.change_before_layer,
        'custom_pla_density_g_cm3':1.30,'custom_density_cli':'PASS','m82_present':'M82' in mode_set,'m83_present':'M83' in mode_set},
      'patches':patch_results,'source_hash_after_patch':source_hash_after,'original_unchanged':True,'firmware_runtime_proven':False}
    (ROOT/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
    return manifest

if __name__=='__main__':
    ap=argparse.ArgumentParser();ap.add_argument('--slicer',type=Path,required=True);args=ap.parse_args()
    print(json.dumps(run(args.slicer),indent=2))
